version: "3.9"
services:
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: infortrend-hands-heat-map
    volumes:
      - ./src:/src
      - ./data:/data
      - ./model:/model
      - ./tmp:/tmp
    command: bash docker-entrypoint.sh
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          capabilities: [gpu]